NDefines_Graphics.NGraphics.BORDER_COLOR_SELECTION_STATE_R = 0.6
NDefines_Graphics.NGraphics.BORDER_COLOR_SELECTION_STATE_G = 0.3
NDefines_Graphics.NGraphics.BORDER_COLOR_SELECTION_STATE_B = 0.0
NDefines_Graphics.NGraphics.BORDER_COLOR_SELECTION_STATE_A = 1.0

NDefines_Graphics.NGraphics.BORDER_COLOR_SELECTION_PROVINCE_R = 1.0
NDefines_Graphics.NGraphics.BORDER_COLOR_SELECTION_PROVINCE_G = 0.8
NDefines_Graphics.NGraphics.BORDER_COLOR_SELECTION_PROVINCE_B = 0.1
NDefines_Graphics.NGraphics.BORDER_COLOR_SELECTION_PROVINCE_A = 1.0

NDefines_Graphics.NGraphics.BORDER_COLOR_DEMILITARIZED_R = 0.01
NDefines_Graphics.NGraphics.BORDER_COLOR_DEMILITARIZED_G = 0.0
NDefines_Graphics.NGraphics.BORDER_COLOR_DEMILITARIZED_B = 0.0
NDefines_Graphics.NGraphics.BORDER_COLOR_DEMILITARIZED_A = 1.0