NDefines.NGraphics.BORDER_COLOR_SELECTION_STATE_R = 1.0
NDefines.NGraphics.BORDER_COLOR_SELECTION_STATE_G = 0.62
NDefines.NGraphics.BORDER_COLOR_SELECTION_STATE_B = 0.33
NDefines.NGraphics.BORDER_COLOR_SELECTION_PROVINCE_R = 1.0
NDefines.NGraphics.BORDER_COLOR_SELECTION_PROVINCE_G = 0.8
NDefines.NGraphics.BORDER_COLOR_SELECTION_PROVINCE_B = 0.0